server:
  port: 9010


spring:
  application:
    name: sentinel
  cloud:
    nacos:
      discovery:
        #        service: provide
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#暴露actuator端点   http://localhost:9010/actuator/sentinel
management:
  endpoints:
    web:
      exposure:
        include: '*'